spring:
  application:
    name: dida
  datasource:
    url: jdbc:mysql://139.155.108.161:3306/Dida?useSSL=false&serverTimezone=UTC&characterEncoding=utf8mb4
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

dida:
  auth-base: https://dida365.com
  api-base: https://api.dida365.com
  client-id: YOUR_CLIENT_ID
  client-secret: YOUR_CLIENT_SECRET
  redirect-uri: http://localhost:8080/oauth/dida/callback

server:
  port: 8080
