spring.application.name=dida
dida:
  auth-base: https://dida365.com
  api-base: https://api.dida365.com
  client-id: YOUR_CLIENT_ID
  client-secret: YOUR_CLIENT_SECRET
  redirect-uri: http://localhost:8080/oauth/dida/callback
server:
  port: 8080
